176036280 add testing that keep value history has effect for all optimizers
zapatacomputing/z-quantum-optimizers pull request #39
Opened 2021-01-04 15:51 UTC by dexter2206

This modifies tests so they are compliant with changes introduced in core. To test, make sure you are using code from the corresponding PR:

zapatacomputing/z-quantum-core#139

2021-01-13 17:31 UTC, mstechly requested changes

2021-01-13 17:31 UTC, mstechly commented on src/python/zquantum/optimizers/grid_search_test.py
>  import unittest
I think this import is unnecessary

2021-01-13 17:31 UTC, mstechly commented on src/python/zquantum/optimizers/scipy_optimizer_test.py
> +])
You're missing COBYLA from here.

2021-01-13 17:31 UTC, mstechly commented on src/python/zquantum/optimizers/scipy_optimizer_test.py
> -    def test_optimizer_succeeds_on_cost_function_without_gradient(self):
Why this one is deleted?

2021-01-13 17:48 UTC, dexter2206 commented on src/python/zquantum/optimizers/scipy_optimizer_test.py
> -    def test_optimizer_succeeds_on_cost_function_without_gradient(self):
Because it is now in the base class :)

2021-01-14 13:28 UTC, dexter2206 commented on src/python/zquantum/optimizers/scipy_optimizer_test.py
> +])
Good catch! Added in e022c70

2021-01-14 13:29 UTC, dexter2206 commented on src/python/zquantum/optimizers/grid_search_test.py
>  import unittest
Fixed in c40d50e

2021-01-14 13:33 UTC, mstechly approved these changes

2021-01-14 13:33 UTC, merged